fix import loop between ganeti.py and reboot.py
We avoid including reboot.py directly because it itself includes
ganeti.py, which creates an import loop which @lavamind stumbled upon
today.

$ ./reboot -v --delay-shutdown 10 -H static-master-fsn.torproject.org
[...]
ImportError: cannot import name 'ShutdownType' from partially initialized module 'fabric_tpa.reboot' (most likely due to a circular import) (/home/jerome/Projets/Tor/tpa/tsa-misc/fabric_tpa/reboot.py)

That bug was introduced in 5402271 and should be fixed, at least I
cannot reproduce it with the above command anymore.