rely on wait_for_shutdown and wait_for_boot instead of custom sleep
I'm honestly pulling at straws now, because Fabric is raising an
exception and I can't figure out where it's coming from:

    All instances migrated successfully.
    Shutdown scheduled for Thu 2020-04-02 18:30:55 UTC, use 'shutdown -c' to cancel.
    waiting 0 minutes for reboot to happen
    waiting up to 30 seconds for host to go down
    waiting 300 seconds for host to go up
    host fsn-node-01.torproject.org should be back online, checking uptime
    Traceback (most recent call last):
      File "./reboot", line 132, in <module>
        logging.getLogger(mod).setLevel('WARNING')
      File "./reboot", line 116, in main
        delay_up=args.delay_up,
      File "/usr/lib/python3/dist-packages/invoke/tasks.py", line 127, in __call__
        result = self.body(*args, **kwargs)
      File "/home/anarcat/src/tor/tsa-misc/fabric_tpa/reboot.py", line 197, in shutdown_and_wait
        res = con.run('uptime', watchers=[responder], pty=True, warn=True)
      File "<decorator-gen-3>", line 2, in run
      File "/usr/lib/python3/dist-packages/fabric/connection.py", line 29, in opens
        self.open()
      File "/home/anarcat/src/tor/tsa-misc/fabric_tpa/__init__.py", line 106, in safe_open
        Connection.open_orig(self)
      File "/usr/lib/python3/dist-packages/fabric/connection.py", line 634, in open
        self.client.connect(**kwargs)
      File "/usr/lib/python3/dist-packages/paramiko/client.py", line 349, in connect
        retry_on_signal(lambda: sock.connect(addr))
      File "/usr/lib/python3/dist-packages/paramiko/util.py", line 280, in retry_on_signal
        return function()
      File "/usr/lib/python3/dist-packages/paramiko/client.py", line 349, in <lambda>
        retry_on_signal(lambda: sock.connect(addr))
    TimeoutError: [Errno 110] Connection timed out

What's strange is that TimeoutError is a OSError, and *should* be
caught by the FabricException:

https://docs.python.org/3.7/library/exceptions.html#TimeoutError